name: guess_party
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.0
  go_router: ^17.0.0
  share_plus: ^12.0.1
  supabase_flutter: ^2.10.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Main_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
